/* Original file date: Apr-1-1997 */

#define IDD_ABOUT                   100
#define IDD_SEARCH                  400
#define IDD_S_RBSTR                 401
#define IDD_S_RBHEX                 402
#define IDD_S_STRENTRY              403
#define IDD_S_HEXENTRY              404
#define IDD_S_WHOLE                 405
#define IDD_S_BACK                  406
#define IDD_COLORS                  500
#define IDD_C_LIST                  501
#define IDD_C_RED                   502
#define IDD_C_GREEN                 503
#define IDD_C_BLUE                  504
#define IDD_C_RECT                  505
#define IDD_C_DEFAULT               507
#define IDD_C_SAMPLE                506
#define IDD_SETTINGS                600
#define IDD_S_NOTEBOOK              601
#define IDD_FONTS                   700
#define IDD_F_FONT                  701
#define IDD_F_SIZE                  702
#define IDD_F_SAMPLE                703
#define IDD_INISPEC                 800
#define IDD_I_FILESPEC              801
#define IDD_I_CHANGE                802
#define ID_NBOK                     510
#define ID_NBCANCEL                 511
#define IDD_LONGNAME                900
#define IDD_L_FILE                  901
#define IDD_L_EA                    902
#define IDD_C_SYSTEM                509
#define IDD_C_CUSTOM                512
#define IDD_GTO_OFF                 1101
#define IDD_ASKVAL                  1000
#define IDD_AV_PRE                  1001
#define IDD_AV_AFTER                1002
#define IDD_ADDEA                   200
#define IDD_EAA_NAME                201
#define IDD_PRINTSETUP              300
#define IDD_PS_PRINTER              301
#define IDD_PS_ALWAYS               302
#define IDD_PS_FONT                 305
#define IDD_PS_STYLE                306
#define IDD_PS_SIZE                 307
#define IDD_PS_ONLYDEVICE           308
#define IDD_PRINTSTAT               1100
#define IDD_PST_PAGE                1102
#define IDD_PST_NAME                1103
#define IDD_PST_PRINTER             1104
